{% set name = "vulture" %}
{% set version = "2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vulture-{{ version }}.tar.gz
  sha256: f9d8b4ce29c69950d323f21dceab4a4d6c694403dffbed7713c4691057e561fe

build:
  noarch: python
  entry_points:
    - vulture = vulture.core:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - tomli >=1.1.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - vulture
  commands:
    - pip check
    - vulture --help

about:
  home: https://github.com/jendrikseipp/vulture
  summary: Find dead code
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Zeitsperre
    - jakirkham
    - rxm7706
