{% set name = "vulture" %}
{% set version = "1.2" %}
{% set sha256 = "c200a01ec47c05d75c5feffe096aeb85a4d3f0e18563be125fae72c13b584ea5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - vulture = vulture.core:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - vulture

  commands:
    - vulture --help

about:
  home: https://github.com/jendrikseipp/vulture
  license: MIT
  license_file: LICENSE.txt
  summary: 'Find dead code'

extra:
  recipe-maintainers:
    - jakirkham
