{% set name = "vulture" %}
{% set version = "1.1" %}
{% set sha256 = "a72834a8c9cf254f6ba0a64e9053b800e05df8391b1724702a19b00d7d849a43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - vulture = vulture.core:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - vulture

  commands:
    - vulture --help

about:
  home: https://github.com/jendrikseipp/vulture
  license: MIT
  license_file: LICENSE.txt
  summary: 'Find dead code'

extra:
  recipe-maintainers:
    - jakirkham
