{% set name = "vulture" %}
{% set version = "2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vulture-{{ version }}.tar.gz
  sha256: cb8277902a1138deeab796ec5bef7076a6e0248ca3607a3f3dee0b6d9e9b8415

build:
  noarch: python
  entry_points:
    - vulture = vulture.core:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - tomli >=1.1.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - vulture
  commands:
    - pip check
    - vulture --help

about:
  home: https://github.com/jendrikseipp/vulture
  summary: Find dead code
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Zeitsperre
    - jakirkham
    - rxm7706
